---
- name: AS2 - Apache webserver met custom pagina en firewall
  hosts: webservers
  become: yes

  vars:
    apache_custom_port: 8082

  tasks:
    - name: Install Apache webserver
      apt:
        name: apache2
        state: present
        update_cache: yes

    - name: Enable Apache rewrite module
      apache2_module:
        name: rewrite
        state: present
      notify: restart apache

    - name: Configure Apache to listen on custom port
      lineinfile:
        path: /etc/apache2/ports.conf
        regexp: '^Listen'
        line: "Listen {{ apache_custom_port }}"
      notify: restart apache

    - name: Update VirtualHost port
      lineinfile:
        path: /etc/apache2/sites-available/000-default.conf
        regexp: '^<VirtualHost'
        line: "<VirtualHost *:{{ apache_custom_port }}>"
      notify: restart apache

    - name: Deploy custom HTML page
      copy:
        src: templates/index.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: '0644'

    - name: Ensure Apache is running
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Open firewall for Apache port
      ufw:
        rule: allow
        port: "{{ apache_custom_port }}"
        proto: tcp

  handlers:
    - name: restart apache
      service:
        name: apache2
        state: restarted
